
locals {
  // this is the idea of @jcarrol who put this into a lib map. Here we steal his idea
  lib_platform_definitions = {
    "ubuntu_20.04" : {
      "family" : "ubuntu-2004-lts",
      "project" : "ubuntu-os-cloud",
      "filter" : "name = ubuntu-2004-focal-v20*",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "ubuntu",
      "ssh_port" : 22,
    },
    "ubuntu_22.04" : {
      "family" : "ubuntu-2204-lts",
      "project" : "ubuntu-os-cloud",
      "filter" : "name = ubuntu-2204-jammy-v20*",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "ubuntu",
      "ssh_port" : 22,
    },
    "centos_9" : {
      "family" : "centos-stream-9",
      "project" : "centos-cloud",
      "filter" : "name = centos-stream-9-v20*",
      "interface" : "eth0",
      "connection" : "centos",
      "ssh_user" : "ubuntu",
      "ssh_port" : 22,
    },
    "rhel_8" : {
      "family" : "rhel-8",
      "project" : "rhel-cloud",
      "filter" : "name = rhel-8-v20*",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "rhel",
      "ssh_port" : 22,
    },
    "rhel_9" : {
      "family" : "rhel-9",
      "project" : "rhel-cloud",
      "filter" : "name = rhel-9-v20*",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "rhel",
      "ssh_port" : 22,
    },
    "rocky_9" : {
      "family" : "rocky-linux-9",
      "project" : "rocky-linux-cloud",
      "filter" : "name = rocky-linux-9-v20*",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "rocky",
      "ssh_port" : 22,
    },
    "rocky_8" : {
      "family" : "rocky-linux-8",
      "project" : "rocky-linux-cloud",
      "filter" : "name = rocky-linux-8-v20*",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "rocky",
      "ssh_port" : 22,
    },
    "sles_12_sp5" : {
      "family" : "sles-12",
      "project" : "suse-cloud",
      "filter" : "name = sles-12-sp5-v20* AND architecture = x86_64",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "sles",
      "ssh_port" : 22,
    },
    "sles_15_sp5" : {
      "family" : "sles-15-sp5",
      "project" : "suse-cloud",
      "filter" : "name = sles-15-sp5-v20* AND architecture = x86_64",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "sles",
      "ssh_port" : 22,
    },
    "sles_15_sp6" : {
      "family" : "sles-15",
      "project" : "suse-cloud",
      "filter" : "name = sles-15-sp6-v20* AND architecture = x86_64",
      "interface" : "eth0",
      "connection" : "ssh",
      "ssh_user" : "sles",
      "ssh_port" : 22,
    },
    "windows_2022" : {
      "family" : "windows-2022",
      "project" : "windows-cloud",
      "filter" : "name = windows-server-2022-dc-v*",
      "interface" : "Ethernet 3"
      "connection" : "winrm",
      "ssh_user" : "miradmin",
      "winrm_useHTTPS" : true,
      "winrm_insecure" : true,
    },
  }
}
